baseURL: 'https://jpy794.github.io'
homepage: 'https://jpy794.github.io'
defaultContentLanguage: 'zh'
theme: hugo-theme-ladder
title: jpy794
params:
  options:
    showDarkMode: true
    enableMultiLang: false
  darkModeTheme: data-dark-mode
  math: true
  analytics:
    google:
      SiteVerificationTag: hkf8Kk9sh38Hm5TzNLXjKJ-Mb3LCSX4b9e4OZ56KXtw
  social:
    - name: GitHub
      pre: <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/jpy794'
languages:
  zh:
    languageName: 中
    brand: HOME
    author: jpy794
    authorDescription: CS在读划水人
    info: Done is better than perfect.
    menu:
      main:
        - name: 文章
          url: /blog
          weight: 1
        - name: 分类
          url: /tags
          weight: 2
        - name: 历史文章
          url: /archives
          weight: 3
taxonomies:
  series: series
  tag: tags
